server:
  port: 9000
spring:
  application:
    name: cloud-webmagic
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-webmagic?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: 123456
#mybatis plus 设置
mybatis-plus:
#  mapper-locations: classpath:com/lly/cloud/plus/mapper/*.xml
  global-config:
    banner: true # MP3.0自带的banner
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
#      id-type: ASSIGN_ID
      table-underline: true # 默认数据库表下划线命名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    call-setters-on-nulls: true  # 返回类型为Map,显示null对应的字段
  type-aliases-package: com.watercloud.webmagic.entity  # 指定需要扫描的entity包

JWTConfig:
  ISSUER: cloud-webmagic
  SECRET: 01ea098224c7d0d2077c14b9a3a1ed16
  EXPIRE_TIME: 1800000



